# Generated by Django 5.2 on 2025-12-11 03:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Savol matni')),
                ('test_code', models.TextField(help_text='Foydalanuvchi kodini test qilish uchun kod', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Test kodi')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=20, verbose_name='Dasturlash tili')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=20, verbose_name='Qiyinchilik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_questions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Dasturlash Savoli',
                'verbose_name_plural': 'Dasturlash Savollari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Kod')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('error', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('test_result', models.JSONField(blank=True, null=True, verbose_name='Test natijasi')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Ishlash vaqti (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app2.programmingquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Kod Yuborish',
                'verbose_name_plural': 'Kod Yuborishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], default='user', max_length=20, verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Profili',
                'verbose_name_plural': 'Foydalanuvchi Profillari',
            },
        ),
    ]
