# Generated by Django 5.2 on 2025-12-11 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python')], default='python', max_length=20, verbose_name='Dasturlash tili'),
        ),
        migrations.CreateModel(
            name='CodeCompilerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], default='user', max_length=20, verbose_name='Rol')),
                ('total_submissions', models.PositiveIntegerField(default=0, verbose_name='Jami yuborishlar')),
                ('successful_submissions', models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatli yuborishlar')),
                ('success_rate', models.FloatField(default=0, verbose_name='Muvaffaqiyat darajasi (%)')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_compiler_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Code Compiler Profil',
                'verbose_name_plural': 'Code Compiler Profillar',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
