# Generated by Django 5.2 on 2025-12-11 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_programmingquestion_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Python Kod Yuborish', 'verbose_name_plural': 'Python Kod Yuborishlar'},
        ),
        migrations.AlterModelOptions(
            name='programmingquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Python Savol', 'verbose_name_plural': 'Python Savollar'},
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='code',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Python Kodi'),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='language',
            field=models.CharField(default='python', editable=False, max_length=20, verbose_name='Dasturlash tili'),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='test_code',
            field=models.TextField(help_text='Foydalanuvchi Python kodini test qilish uchun test kodi', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Test kodi (Python)'),
        ),
    ]
