# Generated by Django 5.2 on 2025-12-15 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_codesubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingquestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='test_result',
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='memory_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='passed_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='test_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='total_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('running', '⚡ Running'), ('passed', '✅ Passed'), ('failed', '❌ Failed'), ('error', '⚠️ Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', '👶 Beginner'), ('easy', '🎯 Easy'), ('medium', '🔥 Medium'), ('hard', '💪 Hard'), ('expert', '👑 Expert')], default='easy', max_length=20)),
                ('function_signature', models.CharField(help_text='def function_name():', max_length=500)),
                ('starter_code', models.TextField(default='', help_text='Default code for user')),
                ('test_framework', models.TextField(default='', help_text='Test framework code')),
                ('test_cases', models.TextField(help_text='Test cases in CodeWars style')),
                ('total_attempts', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app2.codechallenge'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='app2.codesubmission')),
            ],
        ),
        migrations.DeleteModel(
            name='CodeCompilerProfile',
        ),
        migrations.DeleteModel(
            name='ProgrammingQuestion',
        ),
    ]
