# Generated by Django 5.2 on 2025-12-15 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_remove_programmingquestion_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='submission',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Savol sarlavhasi')),
                ('description', models.TextField(verbose_name='Savol matni')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=10)),
                ('test_code', models.TextField(help_text='Foydalanuvchi kodini tekshirish uchun test funksiyasi. Misol: def test_function(user_code): ...', verbose_name='Test kodi')),
                ('example_code', models.TextField(blank=True, help_text='Misol yechim kodi', verbose_name='Namuna kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Kim tomonidan qo'shilgan")),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Yuborilgan kod')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('error', 'Xatolik')], default='pending', max_length=20)),
                ('result_message', models.TextField(blank=True, verbose_name='Natija xabari')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Ishlash vaqti (sek)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.question', verbose_name='Savol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kod yuborish',
                'verbose_name_plural': 'Kod yuborishlar',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='CodeChallenge',
        ),
        migrations.DeleteModel(
            name='CodeSubmission',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
