# Generated by Django 5.2 on 2025-12-15 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_remove_codesubmission_challenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercodesubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usercodesubmission',
            name='user',
        ),
        migrations.CreateModel(
            name='CodeCompilerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], default='user', max_length=20, verbose_name='Rol')),
                ('total_submissions', models.PositiveIntegerField(default=0, verbose_name='Jami yuborishlar')),
                ('successful_submissions', models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatli yuborishlar')),
                ('success_rate', models.FloatField(default=0, verbose_name='Muvaffaqiyat darajasi (%)')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_compiler_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Code Compiler Profil',
                'verbose_name_plural': 'Code Compiler Profillar',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Savol matni')),
                ('test_code', models.TextField(help_text='Foydalanuvchi Python kodini test qilish uchun test kodi', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Test kodi (Python)')),
                ('language', models.CharField(default='python', editable=False, max_length=20, verbose_name='Dasturlash tili')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=20, verbose_name='Qiyinchilik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_questions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Python Savol',
                'verbose_name_plural': 'Python Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Python Kodi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('error', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('test_result', models.JSONField(blank=True, null=True, verbose_name='Test natijasi')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Ishlash vaqti (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app2.programmingquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Python Kod Yuborish',
                'verbose_name_plural': 'Python Kod Yuborishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserCodeSubmission',
        ),
    ]
