# Generated by Django 5.2 on 2025-12-15 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_remove_usercodesubmission_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingquestion',
            name='category',
            field=models.CharField(blank=True, help_text="Savol kategoriyasi (masalan: Matematika, String, Ro'yxat)", max_length=50, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='function_name',
            field=models.CharField(default='solution', help_text="Foydalanuvchi yozishi kerak bo'lgan funksiya nomi (masalan: 'qoshish', 'factorial')", max_length=50, verbose_name='Funksiya nomi'),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='function_params',
            field=models.CharField(default='a, b', help_text="Funksiya parametrlarini kiriting (masalan: 'a, b', 'n', 'text')", max_length=200, verbose_name='Funksiya parametrlari'),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Savolning ball qiymati', verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=20, verbose_name='Qiyinchilik darajasi'),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='question_text',
            field=models.TextField(help_text="Savolning to'liq matnini kiriting", validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='test_code',
            field=models.TextField(help_text='Foydalanuvchi funksiyasini test qilish uchun Python kodi.\nTest kodida <django.db.models.fields.CharField>() funksiyasini chaqiring va assert yordamida tekshiring.\n\nMASALAN:\nresult = <django.db.models.fields.CharField>(5, 3)\nassert result == 8, f"5 + 3 = 8 bo\'lishi kerak, lekin {result} qaytdi"\nprint("✅ Test muvaffaqiyatli!")', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Python Test Kodi'),
        ),
    ]
