# Generated by Django 5.2 on 2025-12-19 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Test mavzusi')),
                ('prompt', models.TextField(blank=True, verbose_name="AI so'rovi")),
                ('ai_response', models.TextField(blank=True, verbose_name='AI javobi')),
                ('questions_data', models.JSONField(default=list, verbose_name="Savollar ma'lumoti")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Test',
                'verbose_name_plural': 'AI Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_questions', models.IntegerField(default=10, verbose_name='Jami savollar')),
                ('time_taken_seconds', models.IntegerField(default=0, verbose_name='Sarflangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.aitest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
