# Generated by Django 5.2 on 2025-11-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('test_file', models.FileField(upload_to='test_files/')),
                ('file_format', models.CharField(choices=[('json', 'JSON Format'), ('txt', 'Text Format')], default='json', max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subject')),
            ],
        ),
    ]
