# Generated by Django 5.2 on 2025-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_question_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='url',
            field=models.TextField(),
        ),
    ]
