# Generated by Django 5.2 on 2025-11-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_videolesson_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolesson',
            old_name='url',
            new_name='iframe_code',
        ),
    ]
