# Generated by Django 5.2 on 2025-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Test qachon tugashi kerak', null=True, verbose_name='Test tugash vaqti'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Test hozir ishlash uchun mavjudmi', verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Test qachon boshlanishi kerak', null=True, verbose_name='Test boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Testni ishlash uchun berilgan vaqt daqiqalarda', verbose_name='Test vaqti (daqiqa)'),
        ),
        migrations.AddField(
            model_name='testfile',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test tugash vaqti'),
        ),
        migrations.AddField(
            model_name='testfile',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='testfile',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Test vaqti (daqiqa)'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Foydalanuvchi testni ishlashga sarflagan vaqt', verbose_name='Sarflangan vaqt (soniya)'),
        ),
    ]
