# Generated by Django 5.2 on 2025-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_test_end_time_test_is_active_test_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='testfile',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='testfile',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Testni ishlash uchun berilgan maksimal vaqt', verbose_name='Test vaqti (daqiqa)'),
        ),
    ]
