# Generated by Django 5.2 on 2025-11-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_question_test_remove_test_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='questions',
        ),
        migrations.AddField(
            model_name='testsession',
            name='question_time_limit_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Har bir savol uchun berilgan maksimal vaqt', verbose_name='Savol vaqti (soniya)'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Testni ishlash uchun berilgan maksimal vaqt', verbose_name='Test vaqti (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='app1.testsession'),
        ),
    ]
