# Generated by Django 5.2 on 2025-11-14 04:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_testsession_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty_level', models.PositiveSmallIntegerField(choices=[(1, 'Oson'), (2, "O'rtacha"), (3, 'Qiyin')], default=2, verbose_name='Qiyinlik darajasi')),
            ],
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='test_session',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='testfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testfile',
            name='file_format',
            field=models.CharField(default='txt', max_length=10),
        ),
        migrations.AddField(
            model_name='testfile',
            name='question_count',
            field=models.PositiveIntegerField(default=25, verbose_name='Savollar soni'),
        ),
        migrations.AddField(
            model_name='testfile',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Test vaqti (daqiqa)'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app1.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30, help_text='Testni ishlash uchun berilgan maksimal vaqt', verbose_name='Test vaqti (daqiqa)')),
                ('is_active', models.BooleanField(default=True, help_text='Test hozir ishlash uchun mavjudmi', verbose_name='Faol')),
                ('question_count', models.PositiveIntegerField(default=25, help_text='Testdagi umumiy savollar soni', verbose_name='Savollar soni')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app1.test'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Foydalanuvchi testni ishlashga sarflagan vaqt', verbose_name='Sarflangan vaqt (soniya)')),
                ('average_difficulty', models.FloatField(default=0, help_text="Testdagi savollarning o'rtacha qiyinlik darajasi", verbose_name="O'rtacha qiyinlik")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.PositiveSmallIntegerField(choices=[(1, 'Oson'), (2, "O'rtacha"), (3, 'Qiyin')], default=2, verbose_name='Qiyinlik darajasi')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi fan darajasi',
                'verbose_name_plural': 'Foydalanuvchi fan darajalari',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
