# Generated by Django 5.2 on 2025-12-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_question_remove_testquestion_user_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test_files/'),
        ),
    ]
