# Generated by Django 5.2 on 2025-12-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_test_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='file',
        ),
    ]
