# Generated by Django 5.2 on 2025-12-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.subject', verbose_name='Fan'),
        ),
    ]
