# Generated by Django 5.2 on 2025-12-18 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_videolesson_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(help_text='Testning aniq mavzusi', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField(help_text="AI ga yuborilgan so'rov")),
                ('ai_response', models.TextField(help_text='AI dan kelgan javob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_count', models.PositiveIntegerField(default=25)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.subject')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_test', to='app1.test')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
