# Generated by Django 5.2 on 2025-12-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_aitestconversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generatedtest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='generatedtest',
            name='test',
        ),
        migrations.CreateModel(
            name='AIGeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mavzu')),
                ('prompt', models.TextField(verbose_name="AI so'rovi")),
                ('ai_response', models.TextField(verbose_name='AI javobi')),
                ('questions_count', models.IntegerField(default=10, verbose_name='Savollar soni')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='medium', max_length=20)),
                ('time_limit_minutes', models.IntegerField(default=30, verbose_name='Vaqt chegarasi (daqiqa)')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Urinishlar soni')),
                ('average_score', models.FloatField(default=0, verbose_name="O'rtacha ball")),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subject', verbose_name='Fan')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.test', verbose_name='Tizim testi')),
            ],
        ),
        migrations.DeleteModel(
            name='AITestConversation',
        ),
        migrations.DeleteModel(
            name='GeneratedTest',
        ),
    ]
