# Generated by Django 5.2 on 2025-12-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_generatedtest_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Test mavzusi')),
                ('questions_data', models.JSONField(verbose_name="Savollar ma'lumoti")),
                ('questions_count', models.IntegerField(default=10, verbose_name='Savollar soni')),
                ('difficulty', models.CharField(default='medium', max_length=20, verbose_name='Qiyinlik')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Urinishlar soni')),
                ('average_score', models.FloatField(default=0, verbose_name="O'rtacha ball")),
                ('time_limit_minutes', models.IntegerField(default=30, verbose_name='Vaqt chegarasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.test')),
            ],
        ),
        migrations.DeleteModel(
            name='AIGeneratedTest',
        ),
    ]
