# Generated by Django 5.2 on 2025-12-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_aitest_delete_aigeneratedtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AITest',
        ),
    ]
